### ISSUE TITLE
Display clear error message when contract not found

### ISSUE THREAD

**Issue by nbanmp** [cleanunicorn/mythos#30]
When analyzing a nonexistent contract, the error message is unclear.

```
> mythos analyze contracts/MetaCoin.sol MetaCoin~
Reading contract contracts/MetaCoin.sol... done
Downloading Solidity version v0.5.6+commit.b259423e
Compiling contract contracts/MetaCoin.sol... done
Analyzing contract MetaCoin~... !
TypeError: Cannot read property 'abi' of undefined
    at Scanner.run (~/.nvm/versions/node/v11.10.0/lib/node_modules/@cleanunicorn/mythos/lib/scanner.js:26:24)
    at Analyze.run (~/.nvm/versions/node/v11.10.0/lib/node_modules/@cleanunicorn/mythos/lib/commands/analyze.js:49:36)
```

**Comment by cleanunicorn** [comment]
Fixed with https://github.com/cleanunicorn/mythos/releases/tag/v0.8.0
